<#
Can also be generated by running:
New-ModuleManifest
#>
@{
    RootModule		= 'ModuleName'
    ModuleVersion	= '0.0.1'
    Author		= 'AuthorName'
    Copyright		= '(c) AuthorName. All rights reserved.'
    Description		= 'Description'
    RequiredModules	= @(

    )
    FunctionsToExport	= '*'
    CmdletsToExport	= '*'
    VariablesToExport	= '*'
    AliasesToExport	= '*'
    PrivateData		= @{
	PSData		= @{
	}
    }
}
